# Generated by Django 4.2.1 on 2023-05-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Boleto'), ('1', 'Pix'), ('2', 'Cartão Débito'), ('3', 'Cartão Crédito')], max_length=1)),
            ],
        ),
    ]
