# Generated by Django 4.2.1 on 2023-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Boleto', 'Boleto'), ('Pix', 'Pix'), ('Cartão Débito', 'Cartão Débito'), ('Cartão Crédito', 'Cartão Crédito')], max_length=14),
        ),
    ]
