# Generated by Django 4.2.1 on 2023-05-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertype_alter_user_options_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='user_type',
            new_name='name',
        ),
    ]
