# Generated by Django 4.2.1 on 2023-05-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='user_type_id',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='name',
            new_name='user_type',
        ),
    ]
