# Generated by Django 4.2.1 on 2023-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_user_type_user_user_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('owner', 'owner'), ('user', 'user')], max_length=6),
        ),
    ]
