# Generated by Django 4.2.1 on 2023-05-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_storeaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(max_length=255)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='reviews')),
            ],
        ),
    ]
