# Generated by Django 4.2.1 on 2023-05-09 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('0', 'Barraquinha'), ('1', 'Restaurante'), ('2', 'Lanchonete'), ('3', 'Only Delivery')], max_length=1)),
                ('is_open', models.BooleanField(default=False)),
                ('is_main_store', models.BooleanField(default=False)),
                ('document_number', models.CharField(max_length=255)),
                ('start_work_hour', models.TimeField()),
                ('close_work_hour', models.TimeField()),
                ('logotype', models.ImageField(upload_to='logotypes/%Y/%m/%d/')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.owner', verbose_name='stores')),
            ],
        ),
    ]
