# Generated by Django 4.2.1 on 2023-05-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('Barraquinha', 'Barraquinha'), ('Restaurante', 'Restaurante'), ('Lanchonete', 'Lanchonete'), ('Only Delivery', 'Only Delivery')], max_length=20),
        ),
    ]
