# Generated by Django 4.2.1 on 2023-05-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_owner_user_id_clientuser'),
        ('stores', '0003_alter_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='profiles.owner'),
        ),
        migrations.AlterField(
            model_name='storeaddress',
            name='store_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='stores.store'),
        ),
    ]
