# Generated by Django 4.2.1 on 2023-05-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_storeaddress'),
        ('payments', '0001_initial'),
        ('profiles', '0002_alter_owner_user_id_clientuser'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Pago'), ('1', 'Cancelado'), ('2', 'Processando'), ('3', 'Ativo')], max_length=1)),
                ('client_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.clientuser', verbose_name='orders')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coupons.coupon', verbose_name='orders')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment', verbose_name='orders')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='orders')),
            ],
        ),
    ]
