# Generated by Django 4.2.1 on 2023-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitems_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Processando', 'Processando'), ('Ativo', 'Ativo')], max_length=12),
        ),
    ]
