# Generated by Django 4.2.1 on 2023-05-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_type'),
        ('profiles', '0002_alter_owner_user_id_clientuser'),
        ('payments', '0002_alter_payment_type'),
        ('products', '0002_alter_category_name'),
        ('coupons', '0003_alter_coupon_value'),
        ('orders', '0005_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.clientuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
    ]
