# Generated by Django 4.2.1 on 2023-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Vegano', 'Vegano'), ('Vegetais', 'Vegetais'), ('Carnes', 'Carnes'), ('Lanches', 'Lanches'), ('Creps', 'Creps'), ('Massas', 'Massas')], max_length=10),
        ),
    ]
